# Spring Boot configuration
spring:
# Database
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-160-120-28.compute-1.amazonaws.com:5432/daocestdfvdtkd
    username: jmhedauvljojik
    password: 17872e71c3df21bf5200ad96eb27b7aac404c394d71e649b2ecd9e858a47ebff
# JPA properties
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true