# Spring Boot configuration
spring:
# Database
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
# JPA properties
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true